Footer
ReCoded-Org/istanbul-capstone-sdp pull request #44
Opened 2020-08-01 21:24 UTC by basil-kawak

PTAL

2020-08-01 21:30 UTC, basil-kawak commented
this is design 
<img width="759" alt="design" src="https://user-images.githubusercontent.com/58145973/89110822-51552800-d457-11ea-8653-5fa93d3cea4e.png">
this is my work
<img width="1440" alt="my work" src="https://user-images.githubusercontent.com/58145973/89110830-5ade9000-d457-11ea-809f-2b1afefeb64c.png">

2020-08-03 09:53 UTC, louisrli requested changes
generally looking good

2020-08-03 09:53 UTC, louisrli commented on src/components/common/Footer.jsx
> +const Footer = () => {
newline above

2020-08-03 09:53 UTC, louisrli commented on src/components/common/Footer.jsx
> +    e.preventDefault();
write something like this, this is how we do it normally: `// TODO(mygithubname): connect this to newsletter`

2020-08-03 09:53 UTC, louisrli commented on src/components/common/Footer.jsx
> +                  placeholder="Enter Your Email Address"
`Your email address`

2020-08-03 09:53 UTC, louisrli commented on src/components/common/Footer.jsx
> +              <Nav.Link href="#" className="icoTwiter" title="Facebook">
`ico` -> `icon` here and everywhere else
typo in twitter

2020-08-03 13:13 UTC, basil-kawak commented
PTAL

2020-08-03 13:15 UTC, louisrli approved these changes
very solid work basil

2020-08-04 03:59 UTC, Samah-Mustafa approved these changes

2020-08-04 12:13 UTC, merged

2020-08-04 12:15 UTC, basil-kawak reviewed
good job