Responsive navbar footer
ReCoded-Org/istanbul-capstone-sdp pull request #74
Opened 2020-08-14 18:03 UTC by Samah-Mustafa

@basil-kawak @maher-suleyman Before reviwing I'm going to fix some issues like classes names

2020-08-17 17:25 UTC, Samah-Mustafa commented
@louisrli PTAL

2020-08-17 17:46 UTC, louisrli requested changes

2020-08-17 17:46 UTC, louisrli commented on src/components/common/LangDropdown.jsx
> +      <Dropdown.Toggle id="dropdown-basic" className="Language-icon">
camel case class name

2020-08-17 17:46 UTC, louisrli commented on src/components/common/NavBar.jsx
> +  const [navItemsPosition, setNavItemsPosition] = React.useState("-100%");
not fixed from earlier comments

2020-08-17 17:46 UTC, louisrli commented on src/components/common/NavBar.jsx
> +  const handleHumburger = () => {
hamburger typo

2020-08-17 18:04 UTC, Samah-Mustafa commented
@louisrli PTAL

2020-08-17 20:06 UTC, basil-kawak commented
@louisrli PTAL

2020-08-17 20:42 UTC, louisrli requested changes

2020-08-17 20:42 UTC, louisrli commented on src/components/common/NavBar.jsx
> +  const handlehamburger = () => {
camelcase

2020-08-17 20:42 UTC, louisrli commented on src/components/common/NavBar.jsx
> +  const [isHamburgerShown, setIsHamburgerShown] = React.useState("-100%");
still same thing

2020-08-17 20:42 UTC, louisrli commented on src/components/common/NavBar.jsx
> +  const [isHamburgerShown, setIsHamburgerShown] = React.useState("-100%");
this should be a boolean

2020-08-17 23:11 UTC, basil-kawak approved these changes
good job

2020-08-17 23:11 UTC, basil-kawak commented on src/containers/App.jsx
> +        {/*learn react*/}
delete this

2020-08-17 23:13 UTC, Samah-Mustafa commented
@louisrli PTAL

2020-08-18 10:03 UTC, louisrli approved these changes
fix classname then its ok

2020-08-18 10:03 UTC, louisrli commented on src/components/common/LangDropdown.jsx
> +      <Dropdown.Toggle id="dropdownBasic" className="LanguageIcon">
camelcase class name

2020-08-18 12:20 UTC, merged